// example/src/Gauge.svelte
<script lang="ts">
  import type { Readable } from 'svelte/store'
  import type { State } from 'xstate'

  export let state: Readable<State<any>>
</script>

<div class="container">
  <div class="gauge-outer" />
  <div class="gauge-inner" class:running={$state.matches('EngineRunning')}>
    <div class="on-off-led">on</div>
    <div class="other-leds">
      <div class="low-fuel-led" class:on={$state.context.lowFuelWarning} />
      <div
        class="low-battery-led"
        class:on={$state.context.lowBatteryWarning}
      />
    </div>
  </div>
  <div
    class="gauge-indicator"
    class:slow={$state.matches('EngineRunning.SlowSpeed')}
    class:fast={$state.matches('EngineRunning.FastSpeed')}
    class:reverse={$state.matches('EngineRunning.Reverse')}
  />
</div>

<style>
  .container {
    position: relative;
    width: 400px;
    height: 200px;
    overflow: hidden;
    text-align: center;
  }
  .gauge-outer {
    z-index: 1;
    position: absolute;
    background-color: var(--base02);
    width: 400px;
    height: 200px;
    top: 0%;
    border-radius: 250px 250px 0px 0px;
  }
  .gauge-inner {
    z-index: 3;
    position: absolute;
    background-color: var(--base03);
    width: 250px;
    height: 125px;
    top: 75px;
    margin-left: 75px;
    margin-right: auto;
    border-radius: 250px 250px 0px 0px;
  }
  .gauge-inner .on-off-led {
    position: relative;
    top: 20px;
    font-size: 20px;
    font-weight: bold;
    color: transparent;
    text-transform: uppercase;
  }
  .gauge-inner.running .on-off-led {
    color: var(--green);
  }
  .gauge-inner .other-leds {
    position: relative;
    top: 50px;
    left: 50px;
    display: flex;
    flex-direction: row;
    height: 40px;
  }
  .gauge-inner .low-fuel-led {
    visibility: hidden;
    width: 30px;
    height: 30px;
    color: transparent;
    background: url('assets/fuel_low.png') no-repeat;
    background-size: 30px 32px;
    background-position: 1px 3px;
  }
  .gauge-inner .low-fuel-led.on {
    visibility: visible;
  }
  .gauge-inner .low-battery-led {
    visibility: hidden;
    width: 30px;
    height: 30px;
    color: transparent;
    background: url('assets/battery_low.png') no-repeat;
    background-size: 30px 30px;
    background-position: 0 3px;
  }
  .gauge-inner .low-battery-led.on {
    visibility: visible;
  }
  .gauge-indicator {
    z-index: 2;
    position: absolute;
    background-color: var(--green);
    width: 400px;
    height: 200px;
    top: 200px;
    margin-left: auto;
    margin-right: auto;
    border-radius: 0px 0px 200px 200px;
    transform-origin: center top;
    transition: all 1.3s ease-in-out;
  }
  .gauge-indicator.slow {
    transform: rotate(60deg);
  }
  .gauge-indicator.fast {
    transform: rotate(150deg);
    background-color: var(--red);
  }
  .gauge-indicator.reverse {
    transform: rotate(20deg);
    background-color: var(--yellow);
  }
  /* .container:hover .gauge-indicator { */
  /*   transform: rotate(0.5turn); */
  /* } */
</style>

// example-react/src/Gauge.tsx
import * as PropTypes from 'prop-types'
import classNames from 'classnames'
import type { State } from 'xstate'
import './Gauge.css'

export default function Gauge({ state }: { state: State<any, any, any, any, any> }) {
  return (
    <div className="container">
      <div className="gauge-outer" />
      <div
        className={classNames('gauge-inner', {
          running: state.matches('EngineRunning'),
        })}
      >
        <div className="on-off-led">on</div>
        <div className="other-leds">
          <div
            className={classNames('low-fuel-led', {
              on: state.context.lowFuelWarning,
            })}
          />
          <div
            className={classNames('low-battery-led', {
              on: state.context.lowBatteryWarning,
            })}
          />
        </div>
      </div>
      <div
        className={classNames('gauge-indicator', {
          slow: state.matches('EngineRunning.SlowSpeed'),
          fast: state.matches('EngineRunning.FastSpeed'),
          reverse: state.matches('EngineRunning.Reverse'),
        })}
      />
    </div>
  )
}

Gauge.propTypes = {
  state: PropTypes.shape({
    matches: PropTypes.func.isRequired,
    context: PropTypes.object,
  }),
}
